// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DataAccess.Models
{
    public partial class Customer
    {
        public Customer()
        {
            Reservation = new HashSet<Reservation>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("person_id")]
        public int? PersonId { get; set; }

        [ForeignKey(nameof(PersonId))]
        [InverseProperty("Customer")]
        public virtual Person Person { get; set; }
        [InverseProperty("Customer")]
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}