// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DataAccess.Models
{
    [Table("Employee_Title")]
    [Index(nameof(Title), Name = "UQ__Employee__E52A1BB32EF0FD0A", IsUnique = true)]
    public partial class EmployeeTitle
    {
        public EmployeeTitle()
        {
            Employee = new HashSet<Employee>();
        }

        [Key]
        [Column("id"), DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        [Column("title")]
        [StringLength(30)]
        public string Title { get; set; }

        [InverseProperty("Title")]
        public virtual ICollection<Employee> Employee { get; set; }
    }
}