// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DataAccess.Models
{
    [Table("Food_Category")]
    public partial class FoodCategory
    {
        public FoodCategory()
        {
            Food = new HashSet<Food>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name")]
        [StringLength(32)]
        public string Name { get; set; }

        [InverseProperty("FoodCategory")]
        public virtual ICollection<Food> Food { get; set; }
    }
}