// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DataAccess.Models
{
    public partial class Food
    {
        public Food()
        {
            OrderLine = new HashSet<OrderLine>();
            Price = new HashSet<Price>();
        }

        [Key]
        [Column("id"), DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        [Column("name")]
        [StringLength(32)]
        public string Name { get; set; }
        [Column("description")]
        [StringLength(500)]
        public string Description { get; set; }
        [Column("food_category_id")]
        public int FoodCategoryId { get; set; }

        [ForeignKey(nameof(FoodCategoryId))]
        [InverseProperty("Food")]
        public virtual FoodCategory FoodCategory { get; set; }
        [InverseProperty("Food")]
        public virtual ICollection<OrderLine> OrderLine { get; set; }
        [InverseProperty("Food")]
        public virtual ICollection<Price> Price { get; set; }
    }
}