// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DataAccess.Models
{
    public partial class OrderLine
    {
        [Column("quantity")]
        public int Quantity { get; set; }
        [Key]
        [Column("food_id")]
        public int FoodId { get; set; }
        [Key]
        [Column("order_Number")]
        public int OrderNumber { get; set; }

        [ForeignKey(nameof(FoodId))]
        [InverseProperty("OrderLine")]
        public virtual Food Food { get; set; }
        [ForeignKey(nameof(OrderNumber))]
        [InverseProperty(nameof(RestaurantOrder.OrderLine))]
        public virtual RestaurantOrder OrderNumberNavigation { get; set; }
    }
}