// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DataAccess.Models
{
    public partial class Price
    {
        [Key]
        [Column("id"), DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Column("price_value", TypeName = "decimal(19, 4)")]
        public decimal PriceValue { get; set; }
        [Column("food_id")]
        public int FoodId { get; set; }

        [ForeignKey(nameof(FoodId))]
        [InverseProperty("Price")]
        public virtual Food Food { get; set; }
    }
}