// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DataAccess.Models
{
    public partial class Reservation
    {
        public Reservation()
        {
            ReservationsTables = new HashSet<ReservationsTables>();
            RestaurantOrder = new HashSet<Order>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("reservation_date", TypeName = "datetime")]
        public DateTime ReservationDate { get; set; }
        [Column("customer_id")]
        public int CustomerId { get; set; }
        [Column("reservationTime")]
        public DateTime ReservationTime { get; set; }
        [Column("noOfPeople")]
        public int NoOfPeople { get; set; }
        [Column("deposit")]
        public bool? Deposit { get; set; }
        [Column("note")]
        [StringLength(200)]
        public string Note { get; set; }

        [ForeignKey(nameof(CustomerId))]
        [InverseProperty("Reservation")]
        public virtual Customer Customer { get; set; }
        [InverseProperty("Reservation")]
        public virtual ICollection<ReservationsTables> ReservationsTables { get; set; }
        [InverseProperty("Reservation")]
        public virtual ICollection<RestaurantOrder> RestaurantOrder { get; set; }
    }
}