// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DataAccess.Models
{
    [Table("Reservations_Tables")]
    public partial class ReservationsTables
    {
        [Key]
        [Column("reservation_id")]
        public int ReservationId { get; set; }
        [Key]
        [Column("restaurant_tables_id")]
        public int RestaurantTablesId { get; set; }

        [ForeignKey(nameof(ReservationId))]
        [InverseProperty("ReservationsTables")]
        public virtual Reservation Reservation { get; set; }
        [ForeignKey(nameof(RestaurantTablesId))]
        [InverseProperty("ReservationsTables")]
        public virtual RestaurantTables RestaurantTables { get; set; }
    }
}