// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DataAccess.Models
{
    [Table("Restaurant_Order")]
    public partial class RestaurantOrder
    {
        public RestaurantOrder()
        {
            OrderLine = new HashSet<OrderLine>();
        }

        [Key]
        [Column("orderNo"), DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int OrderNo { get; set; }
        [Column("reservation_id")]
        public int ReservationId { get; set; }
        [Column("employee_id")]
        public int EmployeeId { get; set; }
        [Column("orderDate", TypeName = "datetime")]
        public DateTime OrderDate { get; set; }
        [Column("paymentCondition_id")]
        public int PaymentConditionId { get; set; }

        [ForeignKey(nameof(EmployeeId))]
        [InverseProperty("RestaurantOrder")]
        public virtual Employee Employee { get; set; }
        [ForeignKey(nameof(PaymentConditionId))]
        [InverseProperty("RestaurantOrder")]
        public virtual PaymentCondition PaymentCondition { get; set; }
        [ForeignKey(nameof(ReservationId))]
        [InverseProperty("RestaurantOrder")]
        public virtual Reservation Reservation { get; set; }
        [InverseProperty("OrderNumberNavigation")]
        public virtual ICollection<OrderLine> OrderLine { get; set; }
    }
}