// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DataAccess.Models
{
    [Table("Restaurant_Tables")]
    public partial class RestaurantTables
    {
        public RestaurantTables()
        {
            ReservationsTables = new HashSet<ReservationsTables>();
        }

        [Key]
        [Column("id"), DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Column("noOfSeats")]
        public int NoOfSeats { get; set; }
        [Column("table_number")]
        public int TableNumber { get; set; }

        [InverseProperty("RestaurantTables")]
        public virtual ICollection<ReservationsTables> ReservationsTables { get; set; }
    }
}