// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DataAccess.Models
{
    [Index(nameof(Username), Name = "UQ__User__F3DBC572E36DAB18", IsUnique = true)]
    public partial class User
    {
        public User()
        {
            Person = new HashSet<Person>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("username")]
        [StringLength(64)]
        public string Username { get; set; }
        [Required]
        [Column("passwordHash")]
        [MaxLength(64)]
        public byte[] PasswordHash { get; set; }
        [Required]
        [Column("salt")]
        [MaxLength(64)]
        public byte[] Salt { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<Person> Person { get; set; }
    }
}