// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DataAccess.Models
{
    [Index(nameof(PersonId), Name = "UQ__User__AA2FFBE40BF2DC7E", IsUnique = true)]
    [Index(nameof(Username), Name = "UQ__User__F3DBC572498F7A30", IsUnique = true)]
    public partial class User
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("username")]
        [StringLength(64)]
        public string Username { get; set; }
        [Required]
        [Column("passwordHash")]
        [MaxLength(64)]
        public byte[] PasswordHash { get; set; }
        [Required]
        [Column("salt")]
        [MaxLength(64)]
        public byte[] Salt { get; set; }
        public int? PersonId { get; set; }

        [ForeignKey(nameof(PersonId))]
        [InverseProperty("User")]
        public virtual Person Person { get; set; }
    }
}